version: '3.6'
services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8083:80"
      - "463:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
  caddy:
    image: caddy:latest
    restart: unless-stopped
    environment:
      BOT_ID: "${TELEGRAM_BOT}"
    ports:
      - "8082:80"
      - "453:443"
    volumes:
      - telegram-bot-api-data:/srv
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy_file/Caddyfile:/etc/caddy/Caddyfile
  telegram-bot-api:
    platform: linux/amd64
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_APP_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_APP_HASH}"
      TELEGRAM_LOCAL: true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081
  postgres:
    image: tobi312/rpi-postgresql-postgis:14-3.1-alpine
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 5433:5432
  graphql-engine:
    image: hasura/graphql-engine:v2.9.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      BOT_ID: "${TELEGRAM_BOT}"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
  telegram-bot-api-data:
  caddy_data:
  caddy_config: